# Generated by Django 5.0.14 on 2026-08-14 08:13

import apps.properties.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.properties.models.property_image_upload_path)),
                ('is_cover', models.BooleanField(default=False, help_text='Shown as the main image in listings and property detail.', verbose_name='Cover image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property image',
                'verbose_name_plural': 'Property images',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['property', 'order'], name='properties__propert_94c164_idx')],
            },
        ),
    ]
