# Generated by Django 5.0.14 on 2026-08-14 11:03

import apps.properties.models
import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_propertyimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('query_params', models.JSONField(default=dict, verbose_name='Search parameters')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('frequency', models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=20, verbose_name='Frequency')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Last sent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Saved search',
                'verbose_name_plural': 'Saved searches',
            },
        ),
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': ['order'], 'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='properties__city_4e3a1c_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='properties__price_32e7c2_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='properties__created_72ecc3_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='properties__propert_16c35e_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='properties__is_acti_2920f7_idx',
        ),
        migrations.RemoveIndex(
            model_name='propertyimage',
            name='properties__propert_94c164_idx',
        ),
        migrations.RemoveField(
            model_name='propertytranslation',
            name='address',
        ),
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold')], default='available', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='property',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='Agent'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Bathrooms'),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='property',
            name='has_air_conditioning',
            field=models.BooleanField(default=False, verbose_name='Air conditioning'),
        ),
        migrations.AlterField(
            model_name='property',
            name='has_elevator',
            field=models.BooleanField(default=False, verbose_name='Elevator'),
        ),
        migrations.AlterField(
            model_name='property',
            name='has_heating',
            field=models.BooleanField(default=False, verbose_name='Heating'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        
        # Primero, convertir la columna manualmente
        migrations.RunSQL(
            sql='ALTER TABLE properties_property ALTER COLUMN location TYPE geometry(Point,4326) USING location::geometry(Point,4326);',
            reverse_sql='ALTER TABLE properties_property ALTER COLUMN location TYPE geometry USING location::geometry;',
        ),
        # Luego, alterar el campo (esto solo actualiza los metadatos de Django)
        migrations.AlterField(
            model_name='property',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, blank=True, null=True, verbose_name='Location'),
        ),
                
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('villa', 'Villa'), ('commercial', 'Commercial'), ('land', 'Land'), ('other', 'Other')], default='apartment', max_length=50, verbose_name='Property type'),
        ),
        migrations.AlterField(
            model_name='property',
            name='province',
            field=models.CharField(blank=True, max_length=100, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='property',
            name='rooms',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Rooms'),
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='property',
            name='surface',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Surface (m²)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Views'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to=apps.properties.models.property_image_upload_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='is_cover',
            field=models.BooleanField(default=False, verbose_name='Cover image'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='Property'),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
