# Generated by Django 5.0.14 on 2026-08-17 12:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_municipality_latitude_municipality_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='property',
            name='properties__price_4f3800_idx',
        ),
        migrations.RemoveField(
            model_name='property',
            name='price',
        ),
        migrations.AddField(
            model_name='property',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Security deposit for rentals', max_digits=12, null=True, verbose_name='Deposit amount'),
        ),
        migrations.AddField(
            model_name='property',
            name='offer_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent'), ('swap', 'Swap'), ('sale_or_rent', 'Sale or Rent')], db_index=True, default='sale', max_length=20, verbose_name='Offer type'),
        ),
        migrations.AddField(
            model_name='property',
            name='rent_price',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, help_text='Required if offering for rent', max_digits=12, null=True, verbose_name='Rent price (monthly)'),
        ),
        migrations.AddField(
            model_name='property',
            name='sale_price',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, help_text='Required if offering for sale', max_digits=12, null=True, verbose_name='Sale price'),
        ),
        migrations.AddField(
            model_name='property',
            name='seasonal_rent_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per day for seasonal rentals', max_digits=12, null=True, verbose_name='Seasonal rent price (daily)'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['sale_price', 'rent_price'], name='properties__sale_pr_eff140_idx'),
        ),
    ]
