# Generated by Django 5.0.14 on 2026-08-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_remove_property_properties__price_4f3800_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='municipality',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='municipality',
            constraint=models.UniqueConstraint(fields=('province', 'name'), name='unique_province_municipality_name'),
        ),
    ]
