# Generated by Django 5.0.14 on 2026-08-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_alter_municipality_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedsearch',
            name='last_sent_at',
        ),
        migrations.AddField(
            model_name='property',
            name='postal_code',
            field=models.CharField(blank=True, db_index=True, help_text='Postal code where the property is located', max_length=10, null=True, verbose_name='Postal code'),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last notified'),
        ),
    ]
