# Generated by Django 5.0.14 on 2026-08-20 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_remove_savedsearch_last_sent_at_property_postal_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='city',
        ),
    ]
