# Generated by Django 5.0.14 on 2026-08-28 15:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_remove_property_city'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='email_contacts_count',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Number of times this property has been contacted via email', verbose_name='Email contacts'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['email_contacts_count'], name='properties__email_c_02502e_idx'),
        ),
    ]
