# Generated by Django 5.0.14 on 2026-08-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_property_email_contacts_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytranslation',
            name='title',
            field=models.CharField(max_length=10000, verbose_name='Title'),
        ),
    ]
