# Generated by Django 5.0.14 on 2026-08-14 11:03

import apps.users.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('buyer', 'Buyer / visitor'), ('agent', 'Agent')], default='buyer', max_length=10, verbose_name='Account type')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Phone')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=apps.users.models.avatar_upload_path, verbose_name='Avatar')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('agency_name', models.CharField(blank=True, max_length=150, verbose_name='Agency name')),
                ('receive_email_alerts', models.BooleanField(default=True, verbose_name='Receive email alerts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User profile',
                'verbose_name_plural': 'User profiles',
            },
        ),
    ]
