# Generated by Django 5.0.14 on 2026-08-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_favorite_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='notified_change_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='snapshot_rent_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='snapshot_sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='snapshot_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
