# Generated by Django 5.0.14 on 2026-08-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogFilterPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('level', models.CharField(blank=True, choices=[('', 'Todos'), ('DEBUG', 'DEBUG'), ('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR'), ('CRITICAL', 'CRITICAL')], max_length=20, verbose_name='nivel')),
                ('search', models.CharField(blank=True, max_length=200, verbose_name='búsqueda')),
                ('lines_per_page', models.PositiveIntegerField(default=100, verbose_name='líneas por página')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
            ],
            options={
                'verbose_name': 'preset de filtro',
                'verbose_name_plural': 'presets de filtros',
                'ordering': ['-created_at'],
            },
        ),
    ]
